### ISSUE TITLE
2aacf7e broke error detection in kak-lsp

### ISSUE THREAD

**Issue by nrdxp** [elm-tooling/elm-language-server#154]
After the recent updates I noticed kakoune was no longer detecting errors in elm files using this language server. Diagnostic warnings still work, but breaking errors are completely ignored. I tried the latest version of the plugin in vscode just to compare and it still works fine there. I ran a `git bisect` to figure out what exactly went wrong and it looks like 2aacf7e448fda9c597cd3ab085739b541452ee47 is where the issue was introduced. It also seems to affect formatting. I can work around that with kakoune's built in format command but the error detection not working is a much bigger PITA.

## Expected Behavior
error detect should work just like it did before the breaking change

## Current Behavior

Errors are not detected at all when running diagnostics in kak-lsp. Warnings still get reported, so unused imports work just fine. But if I call a function that doesn't exist, no error gets reported to the kakoune from the language-server like it used to before 2aacf7e448fda9c597cd3ab085739b541452ee47.

## Steps to Reproduce (for bugs)

1. set kak-lsp following the readme
2. install a version of elm-language server before broken commit E.g 1.2.2
3. call a function that has no definition in an elm file and watch kak-lsp report the error
4. now install the latest version of elm-language-server and see how the error is no longer reported

## Your Environment

* Version used: anything after 2aacf7e448fda9c597cd3ab085739b541452ee47
* Editor used: kakoune
* Environment name and version (e.g. node.js 5.4): node v12.5.0
* Operating System and version: NixOS master

**Comment by Razzeee** [comment]
Interesting. Sounds to me, like kak-lsp does not implement the new settings api?

Anyway, we should fallback to defaults in than case, so I'm surprised. Can you see any logs in kak?

**Comment by nrdxp** [comment]
Nothing really useful. It took me a while to even realize it was the version because the logs were not really helpful even on full verbosity. It just says that `diagnostics were requested` and `Received new elm-analyse report` but it doesn't give any details as to whats actually happened behind that.

**Comment by andys8** [comment]
Might be the cause why [ale](https://github.com/dense-analysis/ale) is also not working with 1.3.2.

https://github.com/neoclide/coc.nvim/blob/f9856a2687d5cb5787d638b19f9417720722bf78/src/language-client/configuration.ts#L19

**Comment by Razzeee** [comment]
Can you test against https://github.com/elm-tooling/elm-language-server/pull/156

You probably need to https://github.com/elm-tooling/elm-language-server#alternative-compile-and-install-from-source with that branch

**Comment by bburdette** [comment]
I'm seeing errors again in kakoune, after 1.4.  I'm on master.at commit 25b126571f238dc3d93f857486368c361317b679.

**Comment by Razzeee** [comment]
Can you be more specific? Which kind of error?

**Comment by bburdette** [comment]
Sorry!  I meant the elm code errors are appearing correctly now in the editor.  Its working again!

**Comment by Razzeee** [comment]
I just released a new version on npm. So I'm closing this for now.
